/*
 * generated by Xtext 2.25.0
 */
package robostar.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CSPMUiModule extends AbstractCSPMUiModule {
	
	override Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return CSPMDefaultAutoEditStrategyProvider
	}
}
