/*
 * generated by Xtext 2.25.0
 */
package robostar.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import robostar.CSPMRuntimeModule
import robostar.CSPMStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CSPMIdeSetup extends CSPMStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CSPMRuntimeModule, new CSPMIdeModule))
	}
	
}
