/*
 * generated by Xtext 2.25.0
 */
package robostar


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CSPMStandaloneSetup extends CSPMStandaloneSetupGenerated {

	def static void doSetup() {
		new CSPMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
